linters-settings:
  errcheck:
    check-type-assertions: true
  goconst:
    min-len: 2
    min-occurrences: 3
  # since upgrading to v1.22.1 of go:
  # ERRO [linters_context] gocritic: load embedded ruleguard
  # rules: rules/rules.go:13: can't load fmt: setting an explicit GOROOT can fix this problem.
  #
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  govet:
    check-shadowing: true
    disable:
      - fieldalignment # too strict

  nolintlint:
    require-explanation: true
    require-specific: true

linters:
  disable-all: true
  enable:
    - bodyclose
    # depguard needs to be reviewed properly and then configured, before
    # it can be re-enabled.
    # https://github.com/OpenPeeDeeP/depguard#example-configs
    # - depguard
    - dogsled
    # - dupl
    - errcheck
    - exportloopref
    - exhaustive
    - goconst
    - gocritic
    - gofmt
    - goimports
    - gomnd
    - gocyclo
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nolintlint
    - nakedret
    - prealloc
    - predeclared
    # - revive // over-bearing for generated code, too many instances
    - staticcheck
    # - structcheck
    - stylecheck
    - thelper
    - tparallel
    - unconvert
    - unparam
    # - varcheck
    - whitespace
    - wsl

run:
  skip-dirs:
    - /generators/gola/templates
  skip-files:
    - .*\.tmpl$
  issues-exit-code: 1
