name: Cobrass Continuous Integration
on:
  push:

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.18.4]
        platform: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.platform }}
    
    steps:
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}

    - name: Install goveralls
      run: go install github.com/mattn/goveralls@latest

    - name: Checkout code
      uses: actions/checkout@v3
    
    - run: go test -v -coverprofile=coverage.out ./...

    - uses: shogo82148/actions-goveralls@v1
      with:
        path-to-profile: coverage.out

    - name: Send coverage
      env:
        COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: goveralls -coverprofile=coverage.out -service=github
